services:
  invoice-nginx:
    image: nginx:1.19.2-alpine
    container_name: invoice-nginx
    hostname: nginx
    volumes:
      - ./cicd/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${EXPOSE_PORT}:${INTERNAL_PORT}"
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - invoice-minio

  invoice-pdf:
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: invoice-pdf
    expose:
      - "${EXPOSE_PORT:-3000}"
    ports:
      - "5680:5680"
    command: yarn dev:debug
    volumes:
      - ./:/usr/src/app

  invoice-minio:
    image: quay.io/minio/minio:latest
    container_name: invoice-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-user1}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-pass09876}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS:-invoices}
    expose:
      - "9000"
      - "9001"
    command: server --console-address ":9001" /data
    hostname: minio
    volumes:
      - ./data:/data
